#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
apt-get update
apt-get install nginx -y
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
systemctl start nginx
