#!/usr/bin/env bash
# Update package lists and install Nginx
apt-get update
apt-get install nginx -y

# Create or overwrite index.html with "Holberton School"
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx without using systemctl
service nginx restart > /dev/null 2>&1
