#!/usr/bin/env bash
# Install Nginx if not already installed
sudo apt update
sudo apt install -y nginx

# Create or modify the redirection configuration file
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Enable the redirection configuration
sudo ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and reload if syntax is okay
sudo nginx -t && sudo systemctl reload nginx
